config/routes.rb
Rails.application.routes.draw do
  resources :houses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:price, :acres, :link, :bedrooms, :studies, :bathrooms, :year_built, :house_modernity, :kitchen_modernity, :internet, :fiber_optic, :water_solved, :sewage_solved, :off_grid, :home_square_feet, :bright, :ac, :house_type, :can_have_livestock, :has_fencing, :fencing_type, :landscape, :barns, :barn_modernity, :road, :worksheds, :houseOverlooksLand, :streams, :stream_year_round, :address, :state, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_with(model: house, local: true) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :house_price %>
  </div>

  <div class="field">
    <%= form.label :acres %>
    <%= form.text_field :acres, id: :house_acres %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_area :link, id: :house_link %>
  </div>

  <div class="field">
    <%= form.label :bedrooms %>
    <%= form.number_field :bedrooms, id: :house_bedrooms %>
  </div>

  <div class="field">
    <%= form.label :studies %>
    <%= form.number_field :studies, id: :house_studies %>
  </div>

  <div class="field">
    <%= form.label :bathrooms %>
    <%= form.number_field :bathrooms, id: :house_bathrooms %>
  </div>

  <div class="field">
    <%= form.label :year_built %>
    <%= form.date_select :year_built, id: :house_year_built %>
  </div>

  <div class="field">
    <%= form.label :house_modernity %>
    <%= form.number_field :house_modernity, id: :house_house_modernity %>
  </div>

  <div class="field">
    <%= form.label :kitchen_modernity %>
    <%= form.number_field :kitchen_modernity, id: :house_kitchen_modernity %>
  </div>

  <div class="field">
    <%= form.label :internet %>
    <%= form.check_box :internet, id: :house_internet %>
  </div>

  <div class="field">
    <%= form.label :fiber_optic %>
    <%= form.check_box :fiber_optic, id: :house_fiber_optic %>
  </div>

  <div class="field">
    <%= form.label :water_solved %>
    <%= form.check_box :water_solved, id: :house_water_solved %>
  </div>

  <div class="field">
    <%= form.label :sewage_solved %>
    <%= form.check_box :sewage_solved, id: :house_sewage_solved %>
  </div>

  <div class="field">
    <%= form.label :off_grid %>
    <%= form.check_box :off_grid, id: :house_off_grid %>
  </div>

  <div class="field">
    <%= form.label :home_square_feet %>
    <%= form.number_field :home_square_feet, id: :house_home_square_feet %>
  </div>

  <div class="field">
    <%= form.label :bright %>
    <%= form.check_box :bright, id: :house_bright %>
  </div>

  <div class="field">
    <%= form.label :ac %>
    <%= form.check_box :ac, id: :house_ac %>
  </div>

  <div class="field">
    <%= form.label :house_type %>
    <%= form.text_field :house_type, id: :house_house_type %>
  </div>

  <div class="field">
    <%= form.label :can_have_livestock %>
    <%= form.check_box :can_have_livestock, id: :house_can_have_livestock %>
  </div>

  <div class="field">
    <%= form.label :has_fencing %>
    <%= form.check_box :has_fencing, id: :house_has_fencing %>
  </div>

  <div class="field">
    <%= form.label :fencing_type %>
    <%= form.text_field :fencing_type, id: :house_fencing_type %>
  </div>

  <div class="field">
    <%= form.label :landscape %>
    <%= form.text_field :landscape, id: :house_landscape %>
  </div>

  <div class="field">
    <%= form.label :barns %>
    <%= form.number_field :barns, id: :house_barns %>
  </div>

  <div class="field">
    <%= form.label :barn_modernity %>
    <%= form.number_field :barn_modernity, id: :house_barn_modernity %>
  </div>

  <div class="field">
    <%= form.label :road %>
    <%= form.text_field :road, id: :house_road %>
  </div>

  <div class="field">
    <%= form.label :worksheds %>
    <%= form.number_field :worksheds, id: :house_worksheds %>
  </div>

  <div class="field">
    <%= form.label :houseOverlooksLand %>
    <%= form.check_box :houseOverlooksLand, id: :house_houseOverlooksLand %>
  </div>

  <div class="field">
    <%= form.label :streams %>
    <%= form.number_field :streams, id: :house_streams %>
  </div>

  <div class="field">
    <%= form.label :stream_year_round %>
    <%= form.check_box :stream_year_round, id: :house_stream_year_round %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :house_address %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :house_state %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :house_city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Acres</th>
      <th>Link</th>
      <th>Bedrooms</th>
      <th>Studies</th>
      <th>Bathrooms</th>
      <th>Year built</th>
      <th>House modernity</th>
      <th>Kitchen modernity</th>
      <th>Internet</th>
      <th>Fiber optic</th>
      <th>Water solved</th>
      <th>Sewage solved</th>
      <th>Off grid</th>
      <th>Home square feet</th>
      <th>Bright</th>
      <th>Ac</th>
      <th>House type</th>
      <th>Can have livestock</th>
      <th>Has fencing</th>
      <th>Fencing type</th>
      <th>Landscape</th>
      <th>Barns</th>
      <th>Barn modernity</th>
      <th>Road</th>
      <th>Worksheds</th>
      <th>Houseoverlooksland</th>
      <th>Streams</th>
      <th>Stream year round</th>
      <th>Address</th>
      <th>State</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.price %></td>
        <td><%= house.acres %></td>
        <td><%= house.link %></td>
        <td><%= house.bedrooms %></td>
        <td><%= house.studies %></td>
        <td><%= house.bathrooms %></td>
        <td><%= house.year_built %></td>
        <td><%= house.house_modernity %></td>
        <td><%= house.kitchen_modernity %></td>
        <td><%= house.internet %></td>
        <td><%= house.fiber_optic %></td>
        <td><%= house.water_solved %></td>
        <td><%= house.sewage_solved %></td>
        <td><%= house.off_grid %></td>
        <td><%= house.home_square_feet %></td>
        <td><%= house.bright %></td>
        <td><%= house.ac %></td>
        <td><%= house.house_type %></td>
        <td><%= house.can_have_livestock %></td>
        <td><%= house.has_fencing %></td>
        <td><%= house.fencing_type %></td>
        <td><%= house.landscape %></td>
        <td><%= house.barns %></td>
        <td><%= house.barn_modernity %></td>
        <td><%= house.road %></td>
        <td><%= house.worksheds %></td>
        <td><%= house.houseOverlooksLand %></td>
        <td><%= house.streams %></td>
        <td><%= house.stream_year_round %></td>
        <td><%= house.address %></td>
        <td><%= house.state %></td>
        <td><%= house.city %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @house.price %>
</p>

<p>
  <strong>Acres:</strong>
  <%= @house.acres %>
</p>

<p>
  <strong>Link:</strong>
  <%= @house.link %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @house.bedrooms %>
</p>

<p>
  <strong>Studies:</strong>
  <%= @house.studies %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @house.bathrooms %>
</p>

<p>
  <strong>Year built:</strong>
  <%= @house.year_built %>
</p>

<p>
  <strong>House modernity:</strong>
  <%= @house.house_modernity %>
</p>

<p>
  <strong>Kitchen modernity:</strong>
  <%= @house.kitchen_modernity %>
</p>

<p>
  <strong>Internet:</strong>
  <%= @house.internet %>
</p>

<p>
  <strong>Fiber optic:</strong>
  <%= @house.fiber_optic %>
</p>

<p>
  <strong>Water solved:</strong>
  <%= @house.water_solved %>
</p>

<p>
  <strong>Sewage solved:</strong>
  <%= @house.sewage_solved %>
</p>

<p>
  <strong>Off grid:</strong>
  <%= @house.off_grid %>
</p>

<p>
  <strong>Home square feet:</strong>
  <%= @house.home_square_feet %>
</p>

<p>
  <strong>Bright:</strong>
  <%= @house.bright %>
</p>

<p>
  <strong>Ac:</strong>
  <%= @house.ac %>
</p>

<p>
  <strong>House type:</strong>
  <%= @house.house_type %>
</p>

<p>
  <strong>Can have livestock:</strong>
  <%= @house.can_have_livestock %>
</p>

<p>
  <strong>Has fencing:</strong>
  <%= @house.has_fencing %>
</p>

<p>
  <strong>Fencing type:</strong>
  <%= @house.fencing_type %>
</p>

<p>
  <strong>Landscape:</strong>
  <%= @house.landscape %>
</p>

<p>
  <strong>Barns:</strong>
  <%= @house.barns %>
</p>

<p>
  <strong>Barn modernity:</strong>
  <%= @house.barn_modernity %>
</p>

<p>
  <strong>Road:</strong>
  <%= @house.road %>
</p>

<p>
  <strong>Worksheds:</strong>
  <%= @house.worksheds %>
</p>

<p>
  <strong>Houseoverlooksland:</strong>
  <%= @house.houseOverlooksLand %>
</p>

<p>
  <strong>Streams:</strong>
  <%= @house.streams %>
</p>

<p>
  <strong>Stream year round:</strong>
  <%= @house.stream_year_round %>
</p>

<p>
  <strong>Address:</strong>
  <%= @house.address %>
</p>

<p>
  <strong>State:</strong>
  <%= @house.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @house.city %>
</p>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeFilter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>